version: '3'
services:
  pilotapi2:
    build: .
    ports:
     - "3001:3001"
    env_file:
     - .env
    # Volumes need to be specified explicitly as there
    # is no way to exclude node_modules
    volumes:
     - ./routes:/usr/src/app/routes
     - ./server.js:/usr/src/app/server.js
    depends_on:
     - redis
    networks:
     - redis
  redis:
    image: redis
    networks:
    - redis
networks:
  redis:
    driver: bridge